Feature/ship page
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #10
Opened 2023-10-12 09:11 UTC by No3ml3

2023-10-12 09:12 UTC, JorisPineau submitted a review, later dismissed

2023-10-12 09:12 UTC, bugBuster42 approved these changes

2023-10-12 10:03 UTC, JorisPineau submitted a review, later dismissed

2023-10-12 10:18 UTC, JorisPineau approved these changes

2023-10-13 08:00 UTC, YDrogen requested changes

2023-10-13 10:17 UTC, bugBuster42 approved these changes

2023-10-13 10:17 UTC, JorisPineau approved these changes

2023-10-13 10:23 UTC, YDrogen requested changes

2023-10-13 10:23 UTC, YDrogen commented on public/shipPlaceHolder.jpg
Nom de fichier en kebab-case !

2023-10-13 10:23 UTC, YDrogen commented on src/components/pages/Ships.jsx
> +    let url = `https://swapi.dev/api/starships/?page=${activePage}`;
Pourquoi `let` ?

2023-10-13 10:23 UTC, YDrogen commented on src/components/fetch/getInfo.jsx
> +  return await res.json();
Le `await` ne sert à rien après un `return`

2023-10-13 10:23 UTC, YDrogen commented on src/components/getImage.jsx
Le nom du fichier doit matcher avec le nom du component

2023-10-13 10:23 UTC, YDrogen commented on src/components/SmallCard.jsx
> +          {<ImageWithFallback fallback={fallBack} src={image} name={name} />}
Pourquoi des `{}` ?

2023-10-13 10:23 UTC, YDrogen commented on src/components/ShipContent.jsx
> +              fallBack="../shipPlaceHolder.jpg"
à changer aussi du coup

2023-10-13 12:18 UTC, JorisPineau approved these changes

2023-10-13 12:24 UTC, YDrogen requested changes

2023-10-13 12:24 UTC, YDrogen commented on public/ship-place-holder.jpg
`placeholder` en un seul mot :(

2023-10-13 12:24 UTC, YDrogen commented on src/components/GetImage.jsx
Du coup c'était plutôt l'inverse : `ImageWithFallback`

2023-10-13 12:24 UTC, YDrogen commented on src/components/SmallCard.jsx
> +export default function Smallcard({ image, name, role, fallBack }) {
```suggestion
export default function Smallcard({ image, name, role, fallback }) {
```

fallback en minuscule

2023-10-13 12:40 UTC, JorisPineau approved these changes

2023-10-13 12:46 UTC, YDrogen requested changes

2023-10-13 12:46 UTC, YDrogen commented on src/components/ShipContent.jsx
> +              fallback="../ship-placeholder.jpg"
`/public/` = `http://localhost:5173/`
Donc `../` ne fonctionnera pas
-> `/ship-placeholder.jpg`

2023-10-13 13:22 UTC, YDrogen approved these changes

2023-10-13 13:22 UTC, merged