Feature/characters
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #13
Opened 2023-10-13 08:39 UTC by bugBuster42

2023-10-13 08:39 UTC, JorisPineau submitted a review, later dismissed

2023-10-26 12:57 UTC, No3ml3 approved these changes

2023-10-26 13:20 UTC, Kaivela commented on src/components/pages/Home.jsx
>            image="image1.jpg"
un new array.fill().map() serait pas mal ici pour éviter de la répétition de code ?

2023-10-26 13:21 UTC, Kaivela approved these changes

2023-10-26 14:02 UTC, YDrogen requested changes

2023-10-26 14:02 UTC, YDrogen commented on src/components/CharacterScrollingCard.jsx
> +        });
Le `forEach` n'est pas nécessaire, tu peux faire un map
```jsx
const coucou = data.results.map((c) => {
  const image = ''; // logique de l'image

  return {
    name: c.name,
    image,
    height: c.height,
  };
}
// setCharactersData(prev => [...prev, ...coucou]) :D
```

2023-10-26 14:02 UTC, YDrogen commented on src/main.css
> +  }
Il y a déjà une class `.perspective` qui a 350px de perspective, ça ne suffit pas ?
Il suffirait de faire une class `.rotate-x-35` pour la rotation

2023-10-26 15:21 UTC, No3ml3 approved these changes

2023-10-27 09:59 UTC, YDrogen requested changes

2023-10-27 09:59 UTC, YDrogen commented on src/components/CharacterScrollingCard.jsx
> +        const newCharactersData = data.results.map((Character) => {
Pourquoi la majuscule ?
`Character` n'est ni une class ni un component

2023-10-27 09:59 UTC, YDrogen commented on src/components/CharacterScrollingCard.jsx
> +        loadedCount++;
Je crois que cette ligne devrait être dans ton `.map`, vu qu'elle compte le nombre de characters
Ou alors tu peux faire `loadedCount += newCharactersData.length` ce qui serait mieux

2023-10-27 09:59 UTC, YDrogen commented on src/main.css
> +    transform: perspective(350px) rotateX(35deg);
Surtout pas, la class `.perspective` est utilisée ailleurs !
Fais une nouvelle class (avec le bon nommage :eyes: )

2023-10-27 09:59 UTC, YDrogen commented on src/main.css
> +  }
Sert à rien ?

2023-10-30 08:41 UTC, bugBuster42 commented on src/main.css
> +  }
j'ai essayé en retirant ".hide-scrollbar" mais sur ma taille d'écran le scrollbar ré-apparait....

2023-10-30 08:41 UTC, bugBuster42 commented on src/main.css
> +    transform: perspective(350px) rotateX(35deg);
ok, je change le nom pour starWarsOpeningCrawlEffect

2023-10-30 09:28 UTC, No3ml3 approved these changes

2023-10-30 09:45 UTC, YDrogen requested changes

2023-10-30 09:45 UTC, YDrogen commented on src/main.css
> +  .starWarsOpeningCrawlEffect {
Perdu, les noms de class sont censées être en kebab-case

2023-10-30 09:57 UTC, Kaivela approved these changes

2023-10-30 10:43 UTC, YDrogen requested changes

2023-10-30 10:43 UTC, YDrogen commented on src/components/CharacterScrollingCard.jsx
> +        const newCharactersData = data.results.map((Character) => {
⏫

2023-10-30 10:57 UTC, No3ml3 approved these changes

2023-10-30 13:48 UTC, YDrogen approved these changes

2023-10-30 13:48 UTC, merged