Feature/planet page
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #15
Opened 2023-10-18 09:39 UTC by JorisPineau

2023-10-18 09:41 UTC, No3ml3 approved these changes

2023-10-18 10:18 UTC, Kaivela approved these changes

2023-10-18 12:25 UTC, No3ml3 approved these changes

2023-10-18 12:32 UTC, YDrogen requested changes

2023-10-18 12:32 UTC, YDrogen commented on src/components/pages/Planets.jsx
> +  ];
Peut être sortie dans un autre fichier `data.js` par exemple

2023-10-18 12:32 UTC, YDrogen commented on src/main.jsx
> +        <Route path="species" element={<Species />} />
Attention lors de la résolution de conflits, cette route n'est pas censée avoir bougé

2023-10-18 12:32 UTC, YDrogen commented on src/components/NavBar.jsx
> +        {/* <MenuItem url="species" icon={<SpecieIcon />} text="species" /> */}
Attention lors de la résolution de conflits, ce bouton n'est pas censé avoir bougé, ni être commenté

2023-10-19 09:31 UTC, No3ml3 submitted a review, later dismissed

2023-10-19 09:53 UTC, YDrogen requested changes

2023-10-19 09:53 UTC, YDrogen commented on src/components/CarouselPlanets.jsx
> +                    e.target.onerror = null;
Pour info, cette ligne ne marche pas

2023-10-19 09:53 UTC, YDrogen commented on src/components/pages/Planets.jsx
> +        });
Pourquoi pas `setPlanets(data.results)` ?

2023-10-19 09:53 UTC, YDrogen commented on src/components/CarouselPlanets.jsx
> +                  }${i}.jpg`}
Ça fonctionne ça ? C'est quoi le rapport entre l'id de la planète et le numéro de page/l'index dans l'array ?

2023-10-19 10:27 UTC, No3ml3 approved these changes

2023-10-19 12:35 UTC, YDrogen approved these changes

2023-10-19 12:58 UTC, No3ml3 approved these changes

2023-10-19 13:26 UTC, YDrogen approved these changes

2023-10-19 13:26 UTC, merged