Feature/ship look page
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #16
Opened 2023-10-18 12:23 UTC by No3ml3

2023-10-18 12:24 UTC, JorisPineau approved these changes

2023-10-19 07:38 UTC, YDrogen requested changes

2023-10-19 07:38 UTC, YDrogen commented on src/components/pages/Ships.jsx
> +            ];
Pas tip top, c'est plus propre de faire un `.slice`

2023-10-19 07:38 UTC, YDrogen commented on src/components/pages/Ships.jsx
> +            ];
idem

2023-10-19 07:38 UTC, YDrogen commented on tailwind.config.js
> +  safelist: ['h-48', 'overflow-x-hidden'],
Pour le `h` (pour la taille de la card) il faut penser aussi à la valeur par défaut (`h-80`)

2023-10-19 07:38 UTC, YDrogen commented on tailwind.config.js
> +  safelist: ['h-48', 'overflow-x-hidden'],
Pourquoi `overflow-x-hidden` ici ?

2023-10-19 07:52 UTC, JorisPineau approved these changes

2023-10-19 07:52 UTC, bugBuster42 approved these changes

2023-10-19 08:02 UTC, YDrogen requested changes

2023-10-19 08:15 UTC, JorisPineau submitted a review, later dismissed

2023-10-19 08:48 UTC, No3ml3 commented on src/components/ShipContent.jsx
> +import { useState } from 'react';
oui ils ont relu mais ils s'excusent d'avoir laissé passé ça

2023-10-19 10:15 UTC, Kaivela approved these changes

2023-10-19 10:26 UTC, YDrogen approved these changes

2023-10-19 10:26 UTC, merged