Feature/loading
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #17
Opened 2023-10-18 14:43 UTC by No3ml3

2023-10-18 14:45 UTC, JorisPineau approved these changes

2023-10-19 07:40 UTC, YDrogen requested changes

2023-10-19 07:40 UTC, YDrogen commented on src/components/Loading.jsx
> +  console.log('working');
Hop le `console.log` oublié !

2023-10-19 07:53 UTC, bugBuster42 approved these changes

2023-10-19 08:02 UTC, YDrogen approved these changes

2023-10-19 08:02 UTC, merged