done the vehicule part
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #20
Opened 2023-10-19 12:43 UTC by No3ml3

2023-10-19 12:51 UTC, bugBuster42 approved these changes

2023-10-19 14:26 UTC, JorisPineau approved these changes

2023-10-19 14:54 UTC, YDrogen requested changes

2023-10-19 14:54 UTC, YDrogen commented on src/components/TransportPage.jsx
> +  const [lastObject, setLastObject] = useState(object);
Pourquoi ?

2023-10-19 14:54 UTC, YDrogen commented on src/components/TransportPage.jsx
> +    }
Pourquoi ce `if` ?

2023-10-19 15:04 UTC, Kaivela requested changes

2023-10-19 19:32 UTC, No3ml3 commented on src/components/TransportPage.jsx
> +  }, [activePage, object]);
j'ai demandé à sylvain, il m'a dis quoi faire. on en reparlera demain si tu veux

2023-10-20 07:09 UTC, bugBuster42 approved these changes

2023-10-20 07:36 UTC, JorisPineau approved these changes

2023-10-20 08:49 UTC, YDrogen approved these changes

2023-10-20 08:50 UTC, YDrogen approved these changes

2023-10-20 09:11 UTC, Kaivela approved these changes

2023-10-20 09:39 UTC, merged