Feature/star
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #21
Opened 2023-10-19 14:32 UTC by No3ml3

2023-10-19 14:41 UTC, JorisPineau submitted a review, later dismissed

2023-10-19 14:56 UTC, YDrogen requested changes
Jamais utilisé ?

2023-10-19 14:56 UTC, YDrogen commented on public/my-star.png
`my-star` ?

2023-10-20 09:00 UTC, YDrogen requested changes

2023-10-20 14:07 UTC, JorisPineau approved these changes

2023-10-23 08:52 UTC, YDrogen approved these changes

2023-10-23 08:52 UTC, merged