Feature/footer
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #28
Opened 2023-10-25 12:50 UTC by No3ml3

2023-10-25 13:01 UTC, JorisPineau submitted a review, later dismissed

2023-10-25 13:10 UTC, JorisPineau submitted a review, later dismissed

2023-10-26 08:57 UTC, Kaivela commented on src/components/FilmsFooter.jsx
> +import Loading from './Loading';
loading is defined but never used

2023-10-26 08:57 UTC, Kaivela commented on src/components/FilmsFooter.jsx
> +  '/movie6.jpg',
pourquoi les 4 premiers films utilisent ./ et pas les deux derniers ?

2023-10-26 09:15 UTC, Kaivela approved these changes

2023-10-26 14:07 UTC, YDrogen requested changes

2023-10-26 14:07 UTC, YDrogen commented on public/movie1.jpeg
Ça va 2.5Mo pour une petit image ? 🤨

2023-10-26 14:07 UTC, YDrogen commented on public/movie5.jpg
😨

2023-10-26 14:07 UTC, YDrogen commented on src/components/FilmsFooter.jsx
> +          bool={true}
??

2023-10-26 14:07 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +      {bool && (
??

2023-10-26 14:07 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +            {' '}
espace vide ?

2023-10-26 14:07 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +                  <p className="text-lg leading-7 ">{film.opening_crawl}</p>
espace inutile

2023-10-26 15:11 UTC, Kaivela submitted a review, later dismissed

2023-10-27 11:49 UTC, YDrogen requested changes
Images beaucoup trop grosses
500Ko MAX par image

(+) au dessus

2023-10-27 12:09 UTC, JorisPineau approved these changes

2023-10-27 12:39 UTC, JorisPineau approved these changes

2023-10-27 13:54 UTC, JorisPineau approved these changes

2023-10-28 19:31 UTC, YDrogen approved these changes

2023-10-28 19:32 UTC, merged