Feature/fetch more footer
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #34
Opened 2023-10-30 09:25 UTC by No3ml3

2023-10-30 09:31 UTC, JorisPineau submitted a review, later dismissed

2023-10-30 09:31 UTC, bugBuster42 submitted a review, later dismissed

2023-10-30 09:33 UTC, Kaivela submitted a review, later dismissed

2023-10-30 09:48 UTC, YDrogen commented on src/components/FilmsFooter.jsx
> +  const specie = useGetArray(movies.map((a) => a.species));
Est-ce que ceci permet de charger toutes les données de tous les films ?

2023-10-30 10:26 UTC, JorisPineau submitted a review, later dismissed

2023-10-30 14:38 UTC, YDrogen requested changes

2023-10-30 14:38 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +  const species = useGetArray(Object.values(film)[10]);
Pourquoi `Object.values` ?

2023-10-30 14:38 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +                  <span className="font-bold uppercase"> Planets :</span>
Espace inutile

2023-10-30 14:38 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +                  <span className="font-bold uppercase"> Starships :</span>
Espace inutile

2023-10-30 14:38 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +                  <span className="font-bold uppercase"> Vehicles :</span>
Espace inutile

2023-10-30 14:38 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +                  <span className="font-bold uppercase"> Species :</span>
Espace inutile

2023-10-30 14:38 UTC, YDrogen commented on src/hooks/useGetArray.jsx
> +export default function useGetArray(arrayUrl) {
Pas génial comme nom

2023-10-30 15:02 UTC, JorisPineau approved these changes

2023-10-30 15:19 UTC, YDrogen requested changes

2023-10-30 15:19 UTC, YDrogen commented on src/components/ModalFooter.jsx
> +import useFetchByArray from '../hooks/useFetchByArray';
`useFetchByArray`

2023-10-30 15:19 UTC, YDrogen commented on src/hooks/useFetchByArray.jsx
> +export default function useGetFetchByArray(arrayUrl) {
ou `useGetFetchByArray` ?

2023-10-30 15:22 UTC, JorisPineau approved these changes

2023-10-31 11:09 UTC, YDrogen approved these changes

2023-10-31 11:09 UTC, merged