cardDetail Character added
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #38
Opened 2023-10-30 16:27 UTC by bugBuster42

2023-10-31 08:05 UTC, No3ml3 submitted a review, later dismissed

2023-10-31 11:14 UTC, YDrogen requested changes

2023-10-31 11:14 UTC, YDrogen commented on src/components/CardDetailCharacter.jsx
> +                    src={character.image}
Pourquoi ne pas déconstruire `image` comme les autres props au dessus ?

2023-10-31 11:14 UTC, YDrogen commented on src/components/CardDetailCharacter.jsx
> +                    alt={character.name}
Pourquoi ne pas utiliser la variable déconstruite ?

2023-10-31 11:22 UTC, No3ml3 approved these changes

2023-11-02 08:15 UTC, No3ml3 approved these changes

2023-11-02 08:16 UTC, Kaivela approved these changes

2023-11-02 08:17 UTC, YDrogen approved these changes

2023-11-02 08:17 UTC, merged