Release/v0.1.0
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #40
Opened 2023-10-31 08:22 UTC by No3ml3

2023-10-31 09:52 UTC, Kaivela submitted a review, later dismissed

2023-10-31 10:53 UTC, JorisPineau submitted a review, later dismissed

2023-10-31 10:53 UTC, JorisPineau commented on src/components/CardDetailStarship.jsx
> +                    src={image}
pas bon {image}

2023-10-31 10:53 UTC, JorisPineau commented on src/components/ModalFooter.jsx
> +        className="absolute z-[80] h-screen w-screen -translate-x-[0rem] -translate-y-[48.5rem]"
pourquoi -translate-x-[0rem]

2023-10-31 10:53 UTC, JorisPineau commented on src/components/ModalFooter.jsx
> +              alt={`${image}`}
ca fonctionne pas juste {image}

2023-10-31 10:53 UTC, JorisPineau commented on src/components/MovingStar.jsx
> +          x: initialX,
pourquoi pas x: 0 directement

2023-10-31 10:53 UTC, JorisPineau commented on src/components/pages/Home.jsx
> +        Object.keys(categories).forEach((category, index) => {
c'est quoi Object.keys et pourquoi forEach

2023-10-31 11:02 UTC, JorisPineau approved these changes

2023-10-31 11:04 UTC, Kaivela approved these changes

2023-10-31 11:11 UTC, bugBuster42 submitted a review, later dismissed

2023-11-01 22:42 UTC, Kaivela requested changes

2023-11-01 22:42 UTC, Kaivela commented on src/components/CharacterScrollingCard.jsx
> +        console.error('Erreur lors de la récupération des données:', error);
français

2023-11-02 08:14 UTC, Kaivela approved these changes

2023-11-02 08:16 UTC, bugBuster42 approved these changes

2023-11-02 08:19 UTC, JorisPineau approved these changes

2023-11-02 08:38 UTC, bugBuster42 approved these changes

2023-11-02 09:36 UTC, JorisPineau approved these changes

2023-11-02 09:50 UTC, Kaivela submitted a review, later dismissed

2023-11-02 11:29 UTC, YDrogen requested changes
- nommage des fichiers dans `public`
  - en minuscules
  - en kebab-case
  - `movie-1` par exemple
- erreurs dans la console (ignorer les erreurs 404)

2023-11-02 11:29 UTC, YDrogen commented on src/components/CardDetailSpecie.jsx
> +                    Homeworld :{' '}
Pas d'espace avant les `:` en anglais

2023-11-02 11:29 UTC, YDrogen commented on src/components/fetch/getInfo.jsx
Ne contient pas de JSX, donc pas besoin de `.jsx`
N'a donc pas besoin d'être dans `components`, ce n'est pas un component

2023-11-02 15:30 UTC, Kaivela approved these changes

2023-11-02 16:09 UTC, JorisPineau approved these changes

2023-11-02 16:25 UTC, bugBuster42 approved these changes

2023-11-03 08:59 UTC, YDrogen approved these changes

2023-11-03 08:59 UTC, merged