change to dev
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #41
Opened 2023-10-31 09:33 UTC by No3ml3

2023-10-31 09:53 UTC, Kaivela submitted a review, later dismissed

2023-10-31 11:03 UTC, Kaivela submitted a review, later dismissed

2023-10-31 11:10 UTC, JorisPineau submitted a review, later dismissed

2023-10-31 11:13 UTC, bugBuster42 approved these changes

2023-11-02 08:13 UTC, JorisPineau submitted a review, later dismissed

2023-11-02 09:08 UTC, bugBuster42 approved these changes

2023-11-02 09:48 UTC, JorisPineau submitted a review, later dismissed

2023-11-02 09:50 UTC, Kaivela approved these changes

2023-11-02 16:07 UTC, bugBuster42 submitted a review, later dismissed

2023-11-03 09:21 UTC, JorisPineau submitted a review, later dismissed

2023-11-03 09:52 UTC, YDrogen requested changes

2023-11-03 09:52 UTC, YDrogen commented on src/fetch/getInfo.js
> +      return error;
C'était le comportement voulu, non ?

2023-11-03 10:03 UTC, JorisPineau approved these changes

2023-11-03 10:04 UTC, YDrogen approved these changes

2023-11-03 10:04 UTC, merged