texte defillant + 5 smallCards
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #5
Opened 2023-10-11 12:06 UTC by bugBuster42

2023-10-11 12:08 UTC, No3ml3 submitted a review, later dismissed

2023-10-11 12:12 UTC, Kaivela commented on src/components/pages/Home.jsx
>  import Title from '../text/Title';
ce import n'est plus nécéssaire

2023-10-11 12:16 UTC, Kaivela submitted a review, later dismissed

2023-10-12 09:09 UTC, YDrogen requested changes
Vérifier `prettier`, les checks automatiques ne passent pas

2023-10-12 09:09 UTC, YDrogen commented on src/main.css
Le but de Tailwind étant d'éviter de faire du CSS comme ça : 
[doc sur les animations custom](https://tailwindcss.com/docs/animation#customizing-your-theme)
[doc sur les pseudo elements](https://tailwindcss.com/docs/hover-focus-and-other-states#pseudo-elements)
[doc sur le CSS custom](https://tailwindcss.com/docs/adding-custom-styles#using-css-and-layer)

2023-10-12 09:09 UTC, YDrogen commented on src/components/HomeScrollingText.jsx
> +import React, { useEffect } from 'react';
```suggestion
import { useEffect } from 'react';
```
`import React from 'react';` pas utile

2023-10-12 09:09 UTC, YDrogen commented on src/components/HomeScrollingText.jsx
> +    const element = document.querySelector('.scroll-text-animation');
Pas une bonne idée la manipulation de DOM comme ça avec React
Voir les [ref](https://react.dev/reference/react/useRef#manipulating-the-dom-with-a-ref) React

2023-10-13 08:20 UTC, JorisPineau submitted a review, later dismissed

2023-10-13 14:30 UTC, YDrogen requested changes
+

2023-10-18 13:04 UTC, No3ml3 approved these changes

2023-10-18 13:46 UTC, YDrogen requested changes

2023-10-18 13:46 UTC, YDrogen commented on src/main.css
> +  }
Tout ça peut aller dans les class tailwind
[doc pseudo elements](https://tailwindcss.com/docs/hover-focus-and-other-states#pseudo-elements)

2023-10-18 13:46 UTC, YDrogen commented on src/main.css
> +  .translate-cards-animation-delay {
Il faudrait un nom générique ici comme `animation-delay-40000` par exemple

2023-10-19 09:08 UTC, No3ml3 approved these changes

2023-10-19 10:15 UTC, No3ml3 approved these changes

2023-10-19 10:25 UTC, YDrogen requested changes

2023-10-19 10:25 UTC, YDrogen commented on src/main.css
> +  }
```suggestion
  .animation-delay-40000 {
    animation-delay: 40s;
  }
```
Soit `-40` en secondes, soit `-40000` en ms

2023-10-19 12:11 UTC, No3ml3 approved these changes

2023-10-19 12:34 UTC, YDrogen approved these changes

2023-10-19 12:35 UTC, merged