Feature/card detail
WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c pull request #8
Opened 2023-10-11 13:41 UTC by JorisPineau

2023-10-12 15:15 UTC, No3ml3 approved these changes

2023-10-20 13:54 UTC, No3ml3 commented on src/components/CardDetailPlanet.jsx
> +  console.log(planet);
console.log

2023-10-20 13:55 UTC, No3ml3 commented on src/components/CardDetailPlanet.jsx
> +                    src="../../public/placeholder-planet.png"
si c'est public le path est /placeholder-planet.png pas besoin de mettre tous les slashs et les points avant

2023-10-20 14:21 UTC, No3ml3 approved these changes

2023-10-23 08:51 UTC, YDrogen requested changes
Déplacer les images dans `public`

2023-10-23 08:51 UTC, YDrogen commented on src/App.jsx
> +  };
Peut être sorti hors du component `App` voire même dans un autre fichier

2023-10-23 08:51 UTC, YDrogen commented on src/App.jsx
> +    image: '../src/assets/Chewbacca.jpeg',
Mauvais chemin

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailCharacter.jsx
Tous les chemins d'images sont faux

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailCharacter.jsx
> +                  />
Sert à rien ? `src` vide

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailCharacter.jsx
> +                  <p className="">Character</p>
className vide

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailPlanet.jsx
Idem chemins faux

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailSpecie.jsx
idem

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailSpecie.jsx
> +                  <p className="">species</p>
className vide

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailStarship.jsx
> +                  <p className="">starship</p>
className vide

2023-10-23 08:51 UTC, YDrogen commented on src/components/CardDetailStarship.jsx
idem chemins

2023-10-23 08:51 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
> +  console.log('list residents', listResidents);
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet1-groupe-c/assets/13053644/f6bdc8ce-a53c-4131-8fd4-dae62c54079f)

2023-10-23 08:51 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
Pourquoi dans un dossier `fetch` ?

2023-10-23 08:51 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
> +  }, [residents]);
1. Super lent à exec, toutes les requêtes se font une par une, donc pas ouf
2. Le `controller` sert à rien ici, le but étant d'`abort` dans la fonction cleanup du `useEffect`

2023-10-23 08:51 UTC, YDrogen commented on src/main.css
> +@import url('https://fonts.googleapis.com/css2?family=Blinker&family=Roboto:ital,wght@0,400;0,500;0,700;0,900;1,400;1,500;1,700;1,900&display=swap');
Roboto est importée 2 fois

2023-10-24 12:05 UTC, No3ml3 submitted a review, later dismissed

2023-10-24 14:56 UTC, YDrogen requested changes

2023-10-24 14:56 UTC, YDrogen commented on src/App.jsx
A quoi sert ce fichier ? Il peut être supprimé non ?

2023-10-24 14:56 UTC, YDrogen commented on src/components/CardDetailCharacter.jsx
Chemins toujours faux, surtout pas de chemin relatifs

2023-10-25 07:02 UTC, No3ml3 submitted a review, later dismissed

2023-10-25 09:03 UTC, No3ml3 submitted a review, later dismissed

2023-10-25 09:28 UTC, YDrogen requested changes

2023-10-25 09:28 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
> +      const promises = residents.map((url) => getInfo(url, controller));
Cette const peut être sortie hors du `useEffect`
Ce qui fait que normalement, `residents` n'est plus nécessaire dans l'array de dépendances

2023-10-25 09:28 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
> +        Resident de la planet
Site en anglais ?

2023-10-25 09:29 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
?

2023-10-25 09:29 UTC, YDrogen commented on src/components/fetch/ResidentsPlanet.jsx
?

2023-10-25 12:57 UTC, No3ml3 approved these changes

2023-10-26 13:53 UTC, YDrogen requested changes
autres demandes + haut

2023-10-27 12:17 UTC, No3ml3 approved these changes

2023-10-27 12:23 UTC, No3ml3 approved these changes

2023-10-28 19:29 UTC, YDrogen requested changes

2023-10-28 19:29 UTC, YDrogen commented on src/components/fetch/getInfo.jsx
> +  const res = await fetch(
1. Il y avait des conflits suite à un merge
2. Les conflits ont mal été résolus
3. `fetchPlus` n'est plus utilisé alors qu'il devrait

2023-10-30 08:57 UTC, Kaivela approved these changes

2023-10-30 09:26 UTC, No3ml3 approved these changes

2023-10-30 09:44 UTC, YDrogen approved these changes

2023-10-30 09:44 UTC, merged